//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diakszovetkezet
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentWork
    {
        public string student_id { get; set; }
        public int work_id { get; set; }
        public System.DateTime sw_date { get; set; }
        public int sw_del { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Work Work { get; set; }
    }
}
