//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diakszovetkezet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Companies()
        {
            this.Work = new HashSet<Work>();
        }
    
        public int c_id { get; set; }
        public string c_name { get; set; }
        public string location { get; set; }
        public string c_description { get; set; }
<<<<<<< HEAD
<<<<<<< HEAD:Diakszovetkezet/Companies.cs
        public Nullable<int> c_del { get; set; }
=======
        public int c_del { get; set; }
>>>>>>> Béla:Diakszovetkezet/Companies.cs
=======
        public int c_del { get; set; }
>>>>>>> Béla
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work> Work { get; set; }
    }
}
