//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diakszovetkezet
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTime
    {
        public int s_id { get; set; }
        public string s_username { get; set; }
        public System.DateTime datestart { get; set; }
        public System.DateTime dateend { get; set; }
    
        public virtual User User { get; set; }
    }
}
