//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diakszovetkezet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.StudentTime = new HashSet<StudentTime>();
            this.Work = new HashSet<Work>();
        }
    
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public int role { get; set; }
<<<<<<< HEAD
<<<<<<< HEAD:Diakszovetkezet/Users.cs
        public Nullable<int> del { get; set; }
=======
        public int del { get; set; }
>>>>>>> Béla:Diakszovetkezet/Users.cs
=======
        public int del { get; set; }
>>>>>>> Béla
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTime> StudentTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work> Work { get; set; }
    }
}
